### ISSUE TITLE
Zenodo for large data archive?

### ISSUE THREAD

**Issue by peterk87** [nlapier2/Metalign#15]
[Zenodo](https://zenodo.org/) would allow you to share the required data for Metalign as a single large `tar.gz` with a DOI. It might be useful for releasing updates to the Metalign database.

**Comment by nlapier2** [comment]
I did try to use Zenodo at first, but a combination of the file size limit and extremely slow upload made it infeasible. Ultimately the file size issue remains, but Box was allowing decent upload/download speeds. Have you found a good way to upload large datasets to Zenodo?

**Comment by peterk87** [comment]
Oh that's too bad. Maybe it's an issue of the Zenodo servers being all the way in Europe at CERN and the service being very popular. I haven't recently tried uploading any large files to Zenodo. 

Maybe [Figshare](https://figshare.com/) would be a good alternative? I've seen some groups sharing very large files via what look to be university mirrors (e.g. https://bridges.monash.edu/projects/Metagenomics_Index_Correction/65534). I've also gotten very good download speeds from Figshare with a 1Gbps connection. 

Also I noticed that most of the disk space is used by `data/organism_files` (239 of 275 GB total for `data/`) and I was wondering if the FASTA sequences could be retrieved from a local install of the NCBI nt DB (which could be downloaded with the `update_blastdb.pl` tool installed with BLAST+). 

A command like this could generate the `fna.gz` files:
```bash
$ blastdbcmd -db nt -entry AB620061,AB620062,AB620063,AB620064 \
  | pigz --best -c - \
  > taxid_1000373_genomic.fna.gz
```

If a tab-delimited file of accessions to taxid were provided and the user had the NCBI nt DB installed, users could reconstruct the files in `data/organism_files` with a GNU Parallel one-liner:

```bash
$ parallel --colsep '\t' \
  blastdbcmd -db nt -entry {1} \
  "|" pigz --best -c - \
  ">" taxid_{2}_genomic.fna.gz \
  :::: accessions_to_taxid.tsv
```

Unfortunately, it looks like the `assembly_summary.txt` files on the NCBI genomes FTP site don't have a field with the list of accessions for a genome. So it might be a little work to construct such a file.

Also could the FASTA files be generated as needed during analysis from an nt DB or via download from NCBI? 

Thanks!

**Comment by dkoslicki** [comment]
It may indeed be worth benchmarking this to see if it's faster to download the organisms this way rather than the current method. Note, though, that future releases will include organisms not just in the NCBI database, so we don't want to tie ourselves too tightly to NCBI/BLAST+.

Also, the FASTA files could "technically" be downloaded on the fly, but due to future planned releases allowing for a) custom databases and b) a default database that is a superset of NCBI, this just-in-time download of files may not be possible in all cases (eg. wrappers for downloading from NCBI, JGI, FungiDB, Ensembl, BGI, MG-RAST, etc. and not all have nice API's).

**Comment by peterk87** [comment]
Custom databases and wrapper for getting data from other sources would be great! 

Thanks for the heads up!

**Comment by nlapier2** [comment]
I initially cycled through several ways to download NCBI data before eventually landing on rsync-ing every genome assembly (refseq + genbank + more) and from those picking the genomes to use for the DB (excluding animals and plants) and creating the dbinfo file. I did this because it was the most comprehensive download from NCBI that I knew of. However, as the number of genome assemblies continues to grow, this method may become impractical. When I initially did this, the rsync took about 24 hours and the subsequent build a few more hours.

For the curious, I have a script that does the db build (assuming rsync has already been done), but note that it's not very polished and I don't guarantee that it would create the DB in exactly the same way as it currently appears: https://github.com/nlapier2/Metalign/blob/master/utils/ncbi2db.py

So, I ultimately decided that including a pre-built version of the DB would be simpler and faster for users. However, it is on my to-do list to eventually get the database building script in working order so that users can re-build it themselves. And, as David said, ideally we'll have custom databases and wrappers eventually.

Since the topic has swayed away from Zenodo (though I'll look into Figshare), I'm going to close this issue and open a new one for the DB.

**Comment by peterk87** [comment]
@nlapier2 Thank you for the info. Would it be possible to add the rsync command you used to download the NCBI data to the wiki, readme or the `ncbi2db.py` script? Did you need to use `--include=PATTERN` and `--exclude=PATTERN` to not download absolutely everything? Thanks!

**Comment by nlapier2** [comment]
Sure, I've added the command used as a comment at the top of ncbi2db.py 

I did use excludes for unwanted files such as RNA.

**Comment by peterk87** [comment]
Thank you @nlapier2! That's awesome :+1:
